trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: AzureBuilder
  # name: Azure Pipelines
  # vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - checkout: self
  - script: echo Hello, Solvexia!
  - script: |
      echo Well, good night.
      echo If you do meet Horatio and Marcellus,
      echo The rivals of my watch, bid them make haste.