name: Checkout benchmark SVX
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, Solvexia!
      - name: Run a multi-line script
        run: |
          echo Well, good night.
          echo If you do meet Horatio and Marcellus,
          echo The rivals of my watch, bid them make haste.
